-- 001_base_schema.sql
-- Base schema for an empty Supabase project. Additive only: safe to run
-- once against a fresh project. Do not edit this file after it has been
-- run anywhere — later changes go in a new numbered file.
--
-- Tables:
--   facilities    A care facility (nursing home / community). The top of
--                 the tenancy tree: every profile and resident belongs to
--                 exactly one facility.
--   user_profiles One row per auth.users row, holding the app-specific
--                 fields (role, display name, which facility/nurse ID
--                 they belong to) that Supabase Auth doesn't store.
--   residents     A resident of a facility, as shown on caregiver and
--                 family screens (roster, home dashboard, etc).
--   visit_notes   A caregiver's log entry for a visit/check-in with a
--                 resident (mood, tasks completed, free-text notes).
--   escalations   A concern a caregiver raises about a resident that
--                 needs follow-up; tracked open/resolved.
--   wellbeing_logs Point-in-time wellbeing readings for a resident
--                 (mood/sleep/pain/weight) shown on trend screens.
--   messages      A message sent to/about a resident's care circle.
--   family_visits A scheduled or logged visit by a family member.
--
-- RLS: every table below has row level security enabled, with one
-- development policy granting signed-in (authenticated) users full read
-- and write access. The anon role has no policy on any of these tables,
-- so with RLS enabled it gets no access at all by default.

create extension if not exists pgcrypto;

-- facilities ------------------------------------------------------------

create table if not exists public.facilities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  plan text,
  subscription_status text,
  created_at timestamptz not null default now()
);

alter table public.facilities enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'facilities'
      and policyname = 'facilities_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "facilities_authenticated_all"
      on public.facilities
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- user_profiles -----------------------------------------------------------

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('superadmin', 'admin', 'staff', 'caregiver', 'family')),
  full_name text,
  facility_id uuid references public.facilities (id),
  nurse_id text,
  created_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles'
      and policyname = 'user_profiles_authenticated_all'
  ) then
    create policy "user_profiles_authenticated_all"
      on public.user_profiles
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- residents ---------------------------------------------------------------

create table if not exists public.residents (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  room_number text,
  care_stage text,
  facility_id uuid not null references public.facilities (id),
  created_at timestamptz not null default now()
);

alter table public.residents enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'residents'
      and policyname = 'residents_authenticated_all'
  ) then
    create policy "residents_authenticated_all"
      on public.residents
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- visit_notes ---------------------------------------------------------------

create table if not exists public.visit_notes (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  facility_id uuid references public.facilities (id),
  visit_type text,
  tasks_completed text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.visit_notes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'visit_notes'
      and policyname = 'visit_notes_authenticated_all'
  ) then
    create policy "visit_notes_authenticated_all"
      on public.visit_notes
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- escalations ---------------------------------------------------------------

create table if not exists public.escalations (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  facility_id uuid references public.facilities (id),
  reason text not null,
  is_resolved boolean not null default false,
  outcome text,
  created_at timestamptz not null default now()
);

alter table public.escalations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'escalations'
      and policyname = 'escalations_authenticated_all'
  ) then
    create policy "escalations_authenticated_all"
      on public.escalations
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- wellbeing_logs ---------------------------------------------------------------

create table if not exists public.wellbeing_logs (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  mood integer,
  sleep integer,
  pain integer,
  weight_kg numeric,
  created_at timestamptz not null default now()
);

alter table public.wellbeing_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'wellbeing_logs'
      and policyname = 'wellbeing_logs_authenticated_all'
  ) then
    create policy "wellbeing_logs_authenticated_all"
      on public.wellbeing_logs
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- messages ---------------------------------------------------------------

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid references auth.users (id),
  content text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'messages'
      and policyname = 'messages_authenticated_all'
  ) then
    create policy "messages_authenticated_all"
      on public.messages
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- family_visits ---------------------------------------------------------------

create table if not exists public.family_visits (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  visitor_name text not null,
  scheduled_at timestamptz,
  status text,
  created_at timestamptz not null default now()
);

alter table public.family_visits enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'family_visits'
      and policyname = 'family_visits_authenticated_all'
  ) then
    create policy "family_visits_authenticated_all"
      on public.family_visits
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;
