-- 002_seed_demo.sql
-- Demo data for local development: one facility, three fictional
-- residents, and a few visit notes. Additive only — safe to run once
-- after 001_base_schema.sql on an empty project. Do not edit this file
-- after it has been run anywhere — later changes go in a new numbered file.

insert into public.facilities (id, name, plan, subscription_status)
values
  ('00000000-0000-0000-0000-000000000001', 'Riverside Care Home', 'standard', 'active')
on conflict (id) do nothing;

insert into public.residents (id, first_name, last_name, room_number, care_stage, facility_id)
values
  ('00000000-0000-0000-0000-000000000101', 'Eleanor', 'Whitfield', '12A', 'Independent', '00000000-0000-0000-0000-000000000001'),
  ('00000000-0000-0000-0000-000000000102', 'Harold', 'Munro', '08B', 'Assisted', '00000000-0000-0000-0000-000000000001'),
  ('00000000-0000-0000-0000-000000000103', 'Dorothy', 'Alvarez', '15C', 'Memory Care', '00000000-0000-0000-0000-000000000001')
on conflict (id) do nothing;

insert into public.visit_notes (resident_id, facility_id, visit_type, tasks_completed, notes)
values
  ('00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000001', 'Caregiver Log', '[Mood: Good] - Morning check-in completed', 'Ate full breakfast, joined the morning walk group.'),
  ('00000000-0000-0000-0000-000000000102', '00000000-0000-0000-0000-000000000001', 'Caregiver Log', '[Mood: Okay] - Medication administered', 'Reported mild knee stiffness, otherwise stable.'),
  ('00000000-0000-0000-0000-000000000103', '00000000-0000-0000-0000-000000000001', 'Caregiver Log', '[Mood: Good] - Afternoon check-in completed', 'Enjoyed the music session, recognized two family photos.');
