-- 003_visit_notes_transcript.sql
-- Adds the `transcript` column the build guide and the iOS app use for the
-- full note text (guide 4.1's client list preview, 5.x note capture).
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists transcript text;
