-- 004_client_profile_fields.sql
-- Adds the fields guide 4.2 (client profile) reads: identity, allergies,
-- physician and emergency contacts on residents, plus a medications table
-- (kept separate rather than embedded JSON, matching the iOS app's
-- schema so both clients read the same shape).
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.residents
  add column if not exists date_of_birth date,
  add column if not exists allergies text[] not null default '{}',
  add column if not exists physician_name text,
  add column if not exists physician_email text,
  add column if not exists emergency_contacts jsonb not null default '[]';
-- emergency_contacts shape: [{ name, relationship, phone, priority }]

create table if not exists public.medications (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  name text not null,
  dose text,
  scheduled_times text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.medications enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'medications'
      and policyname = 'medications_authenticated_all'
  ) then
    create policy "medications_authenticated_all"
      on public.medications
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;
