-- 005_seed_client_profile.sql
-- Fills in the 4.2 client profile fields on the three demo residents seeded
-- in 002_seed_demo.sql, and adds a few demo medications. Additive only,
-- safe to run once after 001-004. Do not edit this file after it has been
-- run anywhere — later changes go in a new numbered file.

update public.residents set
  date_of_birth = '1938-04-12',
  allergies = array['Penicillin', 'Shellfish'],
  physician_name = 'Dr. Amara Boateng',
  physician_email = 'amara.boateng@riversideclinic.example',
  emergency_contacts = '[
    {"name": "Grace Whitfield", "relationship": "Daughter", "phone": "+1 555 0101", "priority": 1},
    {"name": "Peter Whitfield", "relationship": "Son", "phone": "+1 555 0102", "priority": 2}
  ]'::jsonb
where id = '00000000-0000-0000-0000-000000000101';

update public.residents set
  date_of_birth = '1945-11-02',
  allergies = '{}',
  physician_name = 'Dr. Samuel Okafor',
  physician_email = 'samuel.okafor@riversideclinic.example',
  emergency_contacts = '[
    {"name": "Linda Munro", "relationship": "Wife", "phone": "+1 555 0201", "priority": 1}
  ]'::jsonb
where id = '00000000-0000-0000-0000-000000000102';

update public.residents set
  date_of_birth = '1941-07-23',
  allergies = array['Latex'],
  physician_name = 'Dr. Amara Boateng',
  physician_email = 'amara.boateng@riversideclinic.example',
  emergency_contacts = '[
    {"name": "Marco Alvarez", "relationship": "Son", "phone": "+1 555 0301", "priority": 1}
  ]'::jsonb
where id = '00000000-0000-0000-0000-000000000103';

insert into public.medications (resident_id, name, dose, scheduled_times, active)
values
  ('00000000-0000-0000-0000-000000000101', 'Amlodipine', '5mg', array['08:00'], true),
  ('00000000-0000-0000-0000-000000000101', 'Atorvastatin', '20mg', array['20:00'], true),
  ('00000000-0000-0000-0000-000000000102', 'Metformin', '500mg', array['08:00', '18:00'], true),
  ('00000000-0000-0000-0000-000000000103', 'Donepezil', '10mg', array['08:00'], true),
  ('00000000-0000-0000-0000-000000000103', 'Sertraline', '50mg', array['08:00'], false);
