-- 006_seed_caregiver_auth_profile.sql
-- Links the demo caregiver PIN login (ID 1234 / PIN 1234) to a profile row.
-- Prerequisite (manual, not SQL): create the matching Supabase Auth user
-- first, in Dashboard > Authentication > Users > Add user:
--   email    staff_1234@aethon.local
--   password PIN-1234
--   check "Auto Confirm User"
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

insert into public.user_profiles (id, role, full_name, facility_id, nurse_id)
select id, 'caregiver', 'Test Caregiver', '00000000-0000-0000-0000-000000000001', '1234'
from auth.users
where email = 'staff_1234@aethon.local'
on conflict (id) do update set
  role = excluded.role,
  full_name = excluded.full_name,
  facility_id = excluded.facility_id,
  nurse_id = excluded.nurse_id;
