-- 007_independence_baseline.sql
-- Adds the five independence-baseline fields (guide 4.3), captured once at
-- enrolment and never edited afterwards.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.residents
  add column if not exists baseline_age integer,
  add column if not exists baseline_lives_alone boolean,
  add column if not exists baseline_condition_count integer,
  add column if not exists baseline_mobility_aid text
    check (baseline_mobility_aid in ('none', 'stick', 'frame', 'wheelchair')),
  add column if not exists baseline_support_note text,
  add column if not exists baseline_recorded_at timestamptz;
