-- 008_care_stage_history.sql
-- Adds the two extra dates on residents.care_stage (guide 4.4: when a
-- carer noticed the change vs. their estimate of when it actually
-- happened) and the care_stage_history table that records every
-- transition, not just the current value.
-- residents.care_stage stores one of: independent, family_supported,
-- professionally_supported, residential. Display labels are mapped in
-- the app, not stored here.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.residents
  add column if not exists care_stage_observed_at timestamptz,
  add column if not exists care_stage_estimated_since timestamptz;

create table if not exists public.care_stage_history (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  from_stage text,
  to_stage text not null,
  observed_at timestamptz not null,
  estimated_since timestamptz not null,
  changed_by uuid references auth.users (id),
  note text,
  created_at timestamptz not null default now()
);

alter table public.care_stage_history enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'care_stage_history'
      and policyname = 'care_stage_history_authenticated_all'
  ) then
    create policy "care_stage_history_authenticated_all"
      on public.care_stage_history
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;
