-- 009_seed_care_stage.sql
-- Normalizes the three demo residents' care_stage to the four raw codes
-- guide 4.4 expects (independent, family_supported,
-- professionally_supported, residential), replacing the placeholder
-- strings 002_seed_demo.sql used, and backfills an initial
-- care_stage_history row for each so the "Since" line has data.
-- Additive only, safe to run once after 001-008. Do not edit this file
-- after it has been run anywhere — later changes go in a new numbered
-- file.

update public.residents set
  care_stage = 'independent',
  care_stage_observed_at = now(),
  care_stage_estimated_since = now() - interval '8 months'
where id = '00000000-0000-0000-0000-000000000101';

update public.residents set
  care_stage = 'professionally_supported',
  care_stage_observed_at = now(),
  care_stage_estimated_since = now() - interval '3 months'
where id = '00000000-0000-0000-0000-000000000102';

update public.residents set
  care_stage = 'residential',
  care_stage_observed_at = now(),
  care_stage_estimated_since = now() - interval '14 months'
where id = '00000000-0000-0000-0000-000000000103';

insert into public.care_stage_history (resident_id, from_stage, to_stage, observed_at, estimated_since, note)
values
  ('00000000-0000-0000-0000-000000000101', null, 'independent', now() - interval '8 months', now() - interval '8 months', 'Enrolled'),
  ('00000000-0000-0000-0000-000000000102', 'independent', 'professionally_supported', now() - interval '3 months', now() - interval '3 months', 'Started daily home care visits'),
  ('00000000-0000-0000-0000-000000000103', 'family_supported', 'residential', now() - interval '14 months', now() - interval '14 months', 'Moved to memory care unit');
