-- 010_voice_capture.sql
-- Adds the fields guide 5.1 (voice capture) writes on visit_notes: who
-- recorded it (there is no carer sign-in identity beyond auth, so both
-- the auth id and a display name are stored) and the transcription
-- pipeline status, which starts 'pending' until 5.2 fills the transcript.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists carer_id uuid references auth.users (id),
  add column if not exists carer_name text,
  add column if not exists transcription_status text
    check (transcription_status in ('pending', 'complete', 'failed'));
