-- 011_visit_notes_realtime.sql
-- Enables Supabase Realtime UPDATE events on visit_notes (guide 5.2): a
-- transcript fills in on the Notes tab without a manual refresh once
-- background transcription completes.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter publication supabase_realtime add table if not exists public.visit_notes;
