-- 012_seed_family_auth_profile.sql
-- Links the demo family-member login to a profile row with role
-- 'family', so LoginScreen's routeUserBasedOnRole sends it to the
-- family app instead of the caregiver app (only 'caregiver', 'staff',
-- 'admin' and 'superadmin' route to the caregiver app).
-- Prerequisite (manual, not SQL): create the matching Supabase Auth user
-- first, in Dashboard > Authentication > Users > Add user:
--   email    family_member123@aethon.local
--   password (whatever you'll sign in with on the family login form)
--   check "Auto Confirm User"
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

insert into public.user_profiles (id, role, full_name)
select id, 'family', 'Test Family Member'
from auth.users
where email = 'family_member123@aethon.local'
on conflict (id) do update set
  role = excluded.role,
  full_name = excluded.full_name;
