-- 013_note_review.sql
-- Adds the note-review fields (guide 5.3): a note with a transcript but a
-- null reviewed_at is unreviewed. raw_transcript preserves the unedited
-- on-device transcription output so the edit distance can be computed
-- against what a carer actually changed.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists raw_transcript text,
  add column if not exists was_edited boolean,
  add column if not exists raw_length integer,
  add column if not exists edit_distance integer,
  add column if not exists reviewed_at timestamptz;
