-- 014_structured_visit_log.sql
-- Adds the optional structured fields guide 5.4 lets a carer set when
-- confirming a note: what kind of visit it was (visit_type, already
-- present as free text from earlier increments — 5.4 just adds a
-- controlled set of values a carer can pick) and which of five tasks
-- were done (tasks, a JSON object of five booleans).
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists tasks jsonb;
