-- 015_health_logs.sql
-- Health observations (guide 6.1): a short, structured record of how a
-- resident is. Every measurement is optional; a row with only a mood is
-- valid. Ranges are input validation only (mood 1-5, sleep 1-5, pain
-- 0-10); nothing evaluates a value.
-- Separate from wellbeing_logs (001), matching the iOS app's plan.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

create table if not exists public.health_logs (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  logged_by uuid references auth.users (id),
  mood integer check (mood between 1 and 5),
  sleep integer check (sleep between 1 and 5),
  pain integer check (pain between 0 and 10),
  weight_kg numeric,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.health_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'health_logs'
      and policyname = 'health_logs_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "health_logs_authenticated_all"
      on public.health_logs
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;
