-- 016_follow_up_prompts.sql
-- Optional "worth asking about next visit" reminders a carer can set when
-- confirming a note (guide 6.3). Notes to self, not assessments; never
-- shown in the family portal.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists ask_about_hearing boolean not null default false,
  add column if not exists ask_about_vision boolean not null default false,
  add column if not exists ask_about_continence boolean not null default false;
