-- 017_physician_escalation.sql
-- Physician escalation (guide 7.1). Raising a note with the physician
-- flags the most recent visit note with the reason, and also records an
-- escalations row (severity 'physician', linked to that note) so it shows
-- up in the same open-escalation lists as other escalations, matching the
-- iOS app's schema plan. Escalations are "recorded", never "sent".
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists physician_flagged boolean not null default false,
  add column if not exists flag_reason text;

alter table public.escalations
  add column if not exists severity text,
  add column if not exists visit_note_id uuid references public.visit_notes (id);
