-- 018_escalation_outcome.sql
-- Escalation outcome (guide 7.2). A note raised with the physician gets an
-- outcome label and the time it was chosen. physician_flagged_at records
-- when it was raised so the outcome bar can say "Raised with physician on
-- [date]" (older flagged rows have null and fall back to the note date).
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists physician_flagged_at timestamptz,
  add column if not exists flag_outcome text,
  add column if not exists flag_outcome_at timestamptz;
