-- 019_shifts.sql
-- Shift handover (guide 7.3). One row per shift a carer starts; ended_at is
-- set when the shift is closed. The handover collects notes by carer_id and
-- created_at within the shift, so visit_notes needs no new column.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

create table if not exists public.shifts (
  id uuid primary key default gen_random_uuid(),
  carer_id uuid references auth.users (id),
  carer_name text,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

alter table public.shifts enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'shifts'
      and policyname = 'shifts_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "shifts_authenticated_all"
      on public.shifts
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;
