-- 020_resident_role.sql
-- Resident app (guide chapter 10). Adds 'resident' as a valid user role and
-- links a resident's login to their residents row.
--
-- NOTE: this file is a deliberate one-off exception to "additive only".
-- user_profiles.role has a CHECK constraint limiting it to the old role
-- list; a check constraint cannot be widened in place, so it is dropped and
-- re-added with 'resident' included. No rows are changed or removed.
-- The constraint is found by its definition rather than by name, because
-- the name was auto-generated.
-- Do not edit this file after it has been run anywhere — later changes go
-- in a new numbered file.

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.user_profiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%role%'
  loop
    execute format('alter table public.user_profiles drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.user_profiles
  add constraint user_profiles_role_check
  check (role in ('superadmin', 'admin', 'staff', 'caregiver', 'family', 'resident'));

alter table public.user_profiles
  add column if not exists resident_id uuid references public.residents (id);
