-- 021_seed_resident_auth_profile.sql
-- Links a demo resident login to a profile row with role 'resident' and to
-- the first resident in the residents table.
-- Prerequisite (manual, not SQL): create the matching Supabase Auth user
-- first, in Dashboard > Authentication > Users > Add user:
--   email    resident_123@aethon.local
--   password (whatever you'll sign in with on the email/password form)
--   check "Auto Confirm User"
-- Run 020 first. Additive only. Do not edit this file after it has been run
-- anywhere — later changes go in a new numbered file.

insert into public.user_profiles (id, role, full_name, resident_id)
select
  u.id,
  'resident',
  (select first_name from public.residents order by created_at limit 1),
  (select id from public.residents order by created_at limit 1)
from auth.users u
where u.email = 'resident_123@aethon.local'
on conflict (id) do update set
  role = excluded.role,
  full_name = excluded.full_name,
  resident_id = excluded.resident_id;
