-- 022_independence_goals.sql
-- Independence goals (guide 10.2). The resident's own words, stored verbatim
-- as an array of { text, family_visible } objects. No status, progress or
-- achieved/failed state exists by design. family_visible defaults to false
-- in the app; family screens only ever read entries where it is true.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.residents
  add column if not exists independence_goals jsonb not null default '[]';
