-- 024_daily_summary.sql
-- Resident daily summary (guide 10.3).
-- 1. medication_acks: one row per dose the resident marks taken or skipped.
--    The screen that writes them is built in 10.4; 10.3 reads them for the
--    "today" status and the consecutive-day streak. Reference only, not a
--    medication administration record.
-- 2. messages gains the columns needed to show a family message to a
--    resident and record that they saw it. The existing `content` column is
--    used as the message body, so no separate body column is added.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

create table if not exists public.medication_acks (
  id uuid primary key default gen_random_uuid(),
  medication_id uuid not null references public.medications (id) on delete cascade,
  resident_id uuid not null references public.residents (id) on delete cascade,
  status text not null check (status in ('taken', 'skipped')),
  acked_at timestamptz not null default now()
);

alter table public.medication_acks enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'medication_acks'
      and policyname = 'medication_acks_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "medication_acks_authenticated_all"
      on public.medication_acks
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

alter table public.messages
  add column if not exists resident_id uuid references public.residents (id) on delete cascade,
  add column if not exists sender_name text,
  add column if not exists sender_role text,
  add column if not exists image_url text,
  add column if not exists acknowledged_at timestamptz;
