-- 025_seed_family_message.sql
-- Adds one demo message from a family member to the first resident (the one
-- linked to resident_123@aethon.local), so the resident home has something
-- to acknowledge. Run 024 first. Safe to run more than once only if you
-- accept extra demo messages. Additive only. Do not edit this file after it
-- has been run anywhere — later changes go in a new numbered file.

insert into public.messages (resident_id, sender_name, sender_role, content)
select id, 'Sarah', 'family', 'Thinking of you today. Looking forward to seeing you on Sunday!'
from public.residents
order by created_at
limit 1;
