-- 026_assistance_requests.sql
-- Assistance requests (guide 10.5). One row per request for help made from
-- the resident home screen, naming the contact chosen for the time of day.
-- delivered records whether a notification actually reached the contact; it
-- stays false until a delivery channel exists (push tokens are out of scope
-- for now), and the resident is told so honestly.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

create table if not exists public.assistance_requests (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  contacted_name text,
  contacted_phone text,
  escalation_level int not null default 1,
  delivered boolean not null default false,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.assistance_requests enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'assistance_requests'
      and policyname = 'assistance_requests_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "assistance_requests_authenticated_all"
      on public.assistance_requests
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;
