-- 027_realtime_publication.sql
-- Makes sure the tables the app subscribes to are in Supabase Realtime.
--
-- 1. visit_notes (guide 5.2): the caregiver profile listens for UPDATE events
--    so a transcript appears without a refresh. 011 was meant to do this, but
--    "alter publication ... add table if not exists" is not valid Postgres, so
--    011 fails with a syntax error and changes nothing. On a fresh database,
--    run 027 even if 011 fails.
-- 2. messages (guide 10.3): the resident home screen listens for INSERT events
--    on messages. No earlier script added messages to Realtime, so new family
--    messages only appeared after a reload.
--
-- Realtime respects row level security, so this exposes nothing that the
-- tables' policies do not already allow.
-- Additive only and safe to re-run: each table is added only if missing.
-- Do not edit this file after it has been run anywhere — later changes go in
-- a new numbered file.

do $$
declare
  t text;
begin
  foreach t in array array['visit_notes', 'messages']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;
