-- One-off reset of the shared Supabase project 'aethon' (Zurich), 27 Sep 2026.
-- NOT a migration: do not run on any other database.
--
-- Why: the database held two designs at once (the build guide's clients /
-- client_id tables and this app's residents / resident_id tables). This app is
-- now the single codebase for iOS and Android, so its schema becomes the only
-- one.
--
-- What it does, in one transaction (any error rolls back everything):
--   A. Moves every table currently in public into schema archive_2026_09_27.
--      Nothing is deleted; undo with: alter table archive_2026_09_27.<name> set schema public;
--   B. Runs docs/sql/001 to 026 unchanged and in order, except 011: its
--      "add table if not exists" is not valid Postgres, so an equivalent
--      guarded block is used instead.
--   C. Lists the resulting tables with row counts.
-- Not touched: auth users and settings, storage (media bucket), the earlier
-- archive schema legacy_colleague.

begin;

-- ===== A. Archive the current public tables =================================
create schema if not exists archive_2026_09_27;
revoke all on schema archive_2026_09_27 from anon, authenticated;

do $$
declare t text;
begin
  -- Take archived tables out of realtime so they no longer broadcast changes.
  for t in select tablename from pg_publication_tables
           where pubname = 'supabase_realtime' and schemaname = 'public'
  loop
    execute format('alter publication supabase_realtime drop table public.%I', t);
  end loop;
  for t in select table_name from information_schema.tables
           where table_schema = 'public' and table_type = 'BASE TABLE'
  loop
    execute format('alter table public.%I set schema archive_2026_09_27', t);
  end loop;
end $$;

-- ===== B. 001_base_schema.sql =========================================
-- 001_base_schema.sql
-- Base schema for an empty Supabase project. Additive only: safe to run
-- once against a fresh project. Do not edit this file after it has been
-- run anywhere — later changes go in a new numbered file.
--
-- Tables:
--   facilities    A care facility (nursing home / community). The top of
--                 the tenancy tree: every profile and resident belongs to
--                 exactly one facility.
--   user_profiles One row per auth.users row, holding the app-specific
--                 fields (role, display name, which facility/nurse ID
--                 they belong to) that Supabase Auth doesn't store.
--   residents     A resident of a facility, as shown on caregiver and
--                 family screens (roster, home dashboard, etc).
--   visit_notes   A caregiver's log entry for a visit/check-in with a
--                 resident (mood, tasks completed, free-text notes).
--   escalations   A concern a caregiver raises about a resident that
--                 needs follow-up; tracked open/resolved.
--   wellbeing_logs Point-in-time wellbeing readings for a resident
--                 (mood/sleep/pain/weight) shown on trend screens.
--   messages      A message sent to/about a resident's care circle.
--   family_visits A scheduled or logged visit by a family member.
--
-- RLS: every table below has row level security enabled, with one
-- development policy granting signed-in (authenticated) users full read
-- and write access. The anon role has no policy on any of these tables,
-- so with RLS enabled it gets no access at all by default.

create extension if not exists pgcrypto;

-- facilities ------------------------------------------------------------

create table if not exists public.facilities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  plan text,
  subscription_status text,
  created_at timestamptz not null default now()
);

alter table public.facilities enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'facilities'
      and policyname = 'facilities_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "facilities_authenticated_all"
      on public.facilities
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- user_profiles -----------------------------------------------------------

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('superadmin', 'admin', 'staff', 'caregiver', 'family')),
  full_name text,
  facility_id uuid references public.facilities (id),
  nurse_id text,
  created_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles'
      and policyname = 'user_profiles_authenticated_all'
  ) then
    create policy "user_profiles_authenticated_all"
      on public.user_profiles
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- residents ---------------------------------------------------------------

create table if not exists public.residents (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  room_number text,
  care_stage text,
  facility_id uuid not null references public.facilities (id),
  created_at timestamptz not null default now()
);

alter table public.residents enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'residents'
      and policyname = 'residents_authenticated_all'
  ) then
    create policy "residents_authenticated_all"
      on public.residents
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- visit_notes ---------------------------------------------------------------

create table if not exists public.visit_notes (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  facility_id uuid references public.facilities (id),
  visit_type text,
  tasks_completed text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.visit_notes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'visit_notes'
      and policyname = 'visit_notes_authenticated_all'
  ) then
    create policy "visit_notes_authenticated_all"
      on public.visit_notes
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- escalations ---------------------------------------------------------------

create table if not exists public.escalations (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  facility_id uuid references public.facilities (id),
  reason text not null,
  is_resolved boolean not null default false,
  outcome text,
  created_at timestamptz not null default now()
);

alter table public.escalations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'escalations'
      and policyname = 'escalations_authenticated_all'
  ) then
    create policy "escalations_authenticated_all"
      on public.escalations
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- wellbeing_logs ---------------------------------------------------------------

create table if not exists public.wellbeing_logs (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  mood integer,
  sleep integer,
  pain integer,
  weight_kg numeric,
  created_at timestamptz not null default now()
);

alter table public.wellbeing_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'wellbeing_logs'
      and policyname = 'wellbeing_logs_authenticated_all'
  ) then
    create policy "wellbeing_logs_authenticated_all"
      on public.wellbeing_logs
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- messages ---------------------------------------------------------------

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid references auth.users (id),
  content text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'messages'
      and policyname = 'messages_authenticated_all'
  ) then
    create policy "messages_authenticated_all"
      on public.messages
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- family_visits ---------------------------------------------------------------

create table if not exists public.family_visits (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  visitor_name text not null,
  scheduled_at timestamptz,
  status text,
  created_at timestamptz not null default now()
);

alter table public.family_visits enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'family_visits'
      and policyname = 'family_visits_authenticated_all'
  ) then
    create policy "family_visits_authenticated_all"
      on public.family_visits
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- ===== B. 002_seed_demo.sql ===========================================
-- 002_seed_demo.sql
-- Demo data for local development: one facility, three fictional
-- residents, and a few visit notes. Additive only — safe to run once
-- after 001_base_schema.sql on an empty project. Do not edit this file
-- after it has been run anywhere — later changes go in a new numbered file.

insert into public.facilities (id, name, plan, subscription_status)
values
  ('00000000-0000-0000-0000-000000000001', 'Riverside Care Home', 'standard', 'active')
on conflict (id) do nothing;

insert into public.residents (id, first_name, last_name, room_number, care_stage, facility_id)
values
  ('00000000-0000-0000-0000-000000000101', 'Eleanor', 'Whitfield', '12A', 'Independent', '00000000-0000-0000-0000-000000000001'),
  ('00000000-0000-0000-0000-000000000102', 'Harold', 'Munro', '08B', 'Assisted', '00000000-0000-0000-0000-000000000001'),
  ('00000000-0000-0000-0000-000000000103', 'Dorothy', 'Alvarez', '15C', 'Memory Care', '00000000-0000-0000-0000-000000000001')
on conflict (id) do nothing;

insert into public.visit_notes (resident_id, facility_id, visit_type, tasks_completed, notes)
values
  ('00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000001', 'Caregiver Log', '[Mood: Good] - Morning check-in completed', 'Ate full breakfast, joined the morning walk group.'),
  ('00000000-0000-0000-0000-000000000102', '00000000-0000-0000-0000-000000000001', 'Caregiver Log', '[Mood: Okay] - Medication administered', 'Reported mild knee stiffness, otherwise stable.'),
  ('00000000-0000-0000-0000-000000000103', '00000000-0000-0000-0000-000000000001', 'Caregiver Log', '[Mood: Good] - Afternoon check-in completed', 'Enjoyed the music session, recognized two family photos.');

-- ===== B. 003_visit_notes_transcript.sql ==============================
-- 003_visit_notes_transcript.sql
-- Adds the `transcript` column the build guide and the iOS app use for the
-- full note text (guide 4.1's client list preview, 5.x note capture).
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists transcript text;

-- ===== B. 004_client_profile_fields.sql ===============================
-- 004_client_profile_fields.sql
-- Adds the fields guide 4.2 (client profile) reads: identity, allergies,
-- physician and emergency contacts on residents, plus a medications table
-- (kept separate rather than embedded JSON, matching the iOS app's
-- schema so both clients read the same shape).
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.residents
  add column if not exists date_of_birth date,
  add column if not exists allergies text[] not null default '{}',
  add column if not exists physician_name text,
  add column if not exists physician_email text,
  add column if not exists emergency_contacts jsonb not null default '[]';
-- emergency_contacts shape: [{ name, relationship, phone, priority }]

create table if not exists public.medications (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  name text not null,
  dose text,
  scheduled_times text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.medications enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'medications'
      and policyname = 'medications_authenticated_all'
  ) then
    create policy "medications_authenticated_all"
      on public.medications
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- ===== B. 005_seed_client_profile.sql =================================
-- 005_seed_client_profile.sql
-- Fills in the 4.2 client profile fields on the three demo residents seeded
-- in 002_seed_demo.sql, and adds a few demo medications. Additive only,
-- safe to run once after 001-004. Do not edit this file after it has been
-- run anywhere — later changes go in a new numbered file.

update public.residents set
  date_of_birth = '1938-04-12',
  allergies = array['Penicillin', 'Shellfish'],
  physician_name = 'Dr. Amara Boateng',
  physician_email = 'amara.boateng@riversideclinic.example',
  emergency_contacts = '[
    {"name": "Grace Whitfield", "relationship": "Daughter", "phone": "+1 555 0101", "priority": 1},
    {"name": "Peter Whitfield", "relationship": "Son", "phone": "+1 555 0102", "priority": 2}
  ]'::jsonb
where id = '00000000-0000-0000-0000-000000000101';

update public.residents set
  date_of_birth = '1945-11-02',
  allergies = '{}',
  physician_name = 'Dr. Samuel Okafor',
  physician_email = 'samuel.okafor@riversideclinic.example',
  emergency_contacts = '[
    {"name": "Linda Munro", "relationship": "Wife", "phone": "+1 555 0201", "priority": 1}
  ]'::jsonb
where id = '00000000-0000-0000-0000-000000000102';

update public.residents set
  date_of_birth = '1941-07-23',
  allergies = array['Latex'],
  physician_name = 'Dr. Amara Boateng',
  physician_email = 'amara.boateng@riversideclinic.example',
  emergency_contacts = '[
    {"name": "Marco Alvarez", "relationship": "Son", "phone": "+1 555 0301", "priority": 1}
  ]'::jsonb
where id = '00000000-0000-0000-0000-000000000103';

insert into public.medications (resident_id, name, dose, scheduled_times, active)
values
  ('00000000-0000-0000-0000-000000000101', 'Amlodipine', '5mg', array['08:00'], true),
  ('00000000-0000-0000-0000-000000000101', 'Atorvastatin', '20mg', array['20:00'], true),
  ('00000000-0000-0000-0000-000000000102', 'Metformin', '500mg', array['08:00', '18:00'], true),
  ('00000000-0000-0000-0000-000000000103', 'Donepezil', '10mg', array['08:00'], true),
  ('00000000-0000-0000-0000-000000000103', 'Sertraline', '50mg', array['08:00'], false);

-- ===== B. 006_seed_caregiver_auth_profile.sql =========================
-- 006_seed_caregiver_auth_profile.sql
-- Links the demo caregiver PIN login (ID 1234 / PIN 1234) to a profile row.
-- Prerequisite (manual, not SQL): create the matching Supabase Auth user
-- first, in Dashboard > Authentication > Users > Add user:
--   email    staff_1234@aethon.local
--   password PIN-1234
--   check "Auto Confirm User"
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

insert into public.user_profiles (id, role, full_name, facility_id, nurse_id)
select id, 'caregiver', 'Test Caregiver', '00000000-0000-0000-0000-000000000001', '1234'
from auth.users
where email = 'staff_1234@aethon.local'
on conflict (id) do update set
  role = excluded.role,
  full_name = excluded.full_name,
  facility_id = excluded.facility_id,
  nurse_id = excluded.nurse_id;

-- ===== B. 007_independence_baseline.sql ===============================
-- 007_independence_baseline.sql
-- Adds the five independence-baseline fields (guide 4.3), captured once at
-- enrolment and never edited afterwards.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.residents
  add column if not exists baseline_age integer,
  add column if not exists baseline_lives_alone boolean,
  add column if not exists baseline_condition_count integer,
  add column if not exists baseline_mobility_aid text
    check (baseline_mobility_aid in ('none', 'stick', 'frame', 'wheelchair')),
  add column if not exists baseline_support_note text,
  add column if not exists baseline_recorded_at timestamptz;

-- ===== B. 008_care_stage_history.sql ==================================
-- 008_care_stage_history.sql
-- Adds the two extra dates on residents.care_stage (guide 4.4: when a
-- carer noticed the change vs. their estimate of when it actually
-- happened) and the care_stage_history table that records every
-- transition, not just the current value.
-- residents.care_stage stores one of: independent, family_supported,
-- professionally_supported, residential. Display labels are mapped in
-- the app, not stored here.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.residents
  add column if not exists care_stage_observed_at timestamptz,
  add column if not exists care_stage_estimated_since timestamptz;

create table if not exists public.care_stage_history (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  from_stage text,
  to_stage text not null,
  observed_at timestamptz not null,
  estimated_since timestamptz not null,
  changed_by uuid references auth.users (id),
  note text,
  created_at timestamptz not null default now()
);

alter table public.care_stage_history enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'care_stage_history'
      and policyname = 'care_stage_history_authenticated_all'
  ) then
    create policy "care_stage_history_authenticated_all"
      on public.care_stage_history
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- ===== B. 009_seed_care_stage.sql =====================================
-- 009_seed_care_stage.sql
-- Normalizes the three demo residents' care_stage to the four raw codes
-- guide 4.4 expects (independent, family_supported,
-- professionally_supported, residential), replacing the placeholder
-- strings 002_seed_demo.sql used, and backfills an initial
-- care_stage_history row for each so the "Since" line has data.
-- Additive only, safe to run once after 001-008. Do not edit this file
-- after it has been run anywhere — later changes go in a new numbered
-- file.

update public.residents set
  care_stage = 'independent',
  care_stage_observed_at = now(),
  care_stage_estimated_since = now() - interval '8 months'
where id = '00000000-0000-0000-0000-000000000101';

update public.residents set
  care_stage = 'professionally_supported',
  care_stage_observed_at = now(),
  care_stage_estimated_since = now() - interval '3 months'
where id = '00000000-0000-0000-0000-000000000102';

update public.residents set
  care_stage = 'residential',
  care_stage_observed_at = now(),
  care_stage_estimated_since = now() - interval '14 months'
where id = '00000000-0000-0000-0000-000000000103';

insert into public.care_stage_history (resident_id, from_stage, to_stage, observed_at, estimated_since, note)
values
  ('00000000-0000-0000-0000-000000000101', null, 'independent', now() - interval '8 months', now() - interval '8 months', 'Enrolled'),
  ('00000000-0000-0000-0000-000000000102', 'independent', 'professionally_supported', now() - interval '3 months', now() - interval '3 months', 'Started daily home care visits'),
  ('00000000-0000-0000-0000-000000000103', 'family_supported', 'residential', now() - interval '14 months', now() - interval '14 months', 'Moved to memory care unit');

-- ===== B. 010_voice_capture.sql =======================================
-- 010_voice_capture.sql
-- Adds the fields guide 5.1 (voice capture) writes on visit_notes: who
-- recorded it (there is no carer sign-in identity beyond auth, so both
-- the auth id and a display name are stored) and the transcription
-- pipeline status, which starts 'pending' until 5.2 fills the transcript.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists carer_id uuid references auth.users (id),
  add column if not exists carer_name text,
  add column if not exists transcription_status text
    check (transcription_status in ('pending', 'complete', 'failed'));

-- ===== B. 011_visit_notes_realtime.sql (guarded equivalent) ================================
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'visit_notes'
  ) then
    alter publication supabase_realtime add table public.visit_notes;
  end if;
end $$;

-- ===== B. 012_seed_family_auth_profile.sql ============================
-- 012_seed_family_auth_profile.sql
-- Links the demo family-member login to a profile row with role
-- 'family', so LoginScreen's routeUserBasedOnRole sends it to the
-- family app instead of the caregiver app (only 'caregiver', 'staff',
-- 'admin' and 'superadmin' route to the caregiver app).
-- Prerequisite (manual, not SQL): create the matching Supabase Auth user
-- first, in Dashboard > Authentication > Users > Add user:
--   email    family_member123@aethon.local
--   password (whatever you'll sign in with on the family login form)
--   check "Auto Confirm User"
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

insert into public.user_profiles (id, role, full_name)
select id, 'family', 'Test Family Member'
from auth.users
where email = 'family_member123@aethon.local'
on conflict (id) do update set
  role = excluded.role,
  full_name = excluded.full_name;

-- ===== B. 013_note_review.sql =========================================
-- 013_note_review.sql
-- Adds the note-review fields (guide 5.3): a note with a transcript but a
-- null reviewed_at is unreviewed. raw_transcript preserves the unedited
-- on-device transcription output so the edit distance can be computed
-- against what a carer actually changed.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists raw_transcript text,
  add column if not exists was_edited boolean,
  add column if not exists raw_length integer,
  add column if not exists edit_distance integer,
  add column if not exists reviewed_at timestamptz;

-- ===== B. 014_structured_visit_log.sql ================================
-- 014_structured_visit_log.sql
-- Adds the optional structured fields guide 5.4 lets a carer set when
-- confirming a note: what kind of visit it was (visit_type, already
-- present as free text from earlier increments — 5.4 just adds a
-- controlled set of values a carer can pick) and which of five tasks
-- were done (tasks, a JSON object of five booleans).
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists tasks jsonb;

-- ===== B. 015_health_logs.sql =========================================
-- 015_health_logs.sql
-- Health observations (guide 6.1): a short, structured record of how a
-- resident is. Every measurement is optional; a row with only a mood is
-- valid. Ranges are input validation only (mood 1-5, sleep 1-5, pain
-- 0-10); nothing evaluates a value.
-- Separate from wellbeing_logs (001), matching the iOS app's plan.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

create table if not exists public.health_logs (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  logged_by uuid references auth.users (id),
  mood integer check (mood between 1 and 5),
  sleep integer check (sleep between 1 and 5),
  pain integer check (pain between 0 and 10),
  weight_kg numeric,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.health_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'health_logs'
      and policyname = 'health_logs_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "health_logs_authenticated_all"
      on public.health_logs
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- ===== B. 016_follow_up_prompts.sql ===================================
-- 016_follow_up_prompts.sql
-- Optional "worth asking about next visit" reminders a carer can set when
-- confirming a note (guide 6.3). Notes to self, not assessments; never
-- shown in the family portal.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists ask_about_hearing boolean not null default false,
  add column if not exists ask_about_vision boolean not null default false,
  add column if not exists ask_about_continence boolean not null default false;

-- ===== B. 017_physician_escalation.sql ================================
-- 017_physician_escalation.sql
-- Physician escalation (guide 7.1). Raising a note with the physician
-- flags the most recent visit note with the reason, and also records an
-- escalations row (severity 'physician', linked to that note) so it shows
-- up in the same open-escalation lists as other escalations, matching the
-- iOS app's schema plan. Escalations are "recorded", never "sent".
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists physician_flagged boolean not null default false,
  add column if not exists flag_reason text;

alter table public.escalations
  add column if not exists severity text,
  add column if not exists visit_note_id uuid references public.visit_notes (id);

-- ===== B. 018_escalation_outcome.sql ==================================
-- 018_escalation_outcome.sql
-- Escalation outcome (guide 7.2). A note raised with the physician gets an
-- outcome label and the time it was chosen. physician_flagged_at records
-- when it was raised so the outcome bar can say "Raised with physician on
-- [date]" (older flagged rows have null and fall back to the note date).
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.visit_notes
  add column if not exists physician_flagged_at timestamptz,
  add column if not exists flag_outcome text,
  add column if not exists flag_outcome_at timestamptz;

-- ===== B. 019_shifts.sql ==============================================
-- 019_shifts.sql
-- Shift handover (guide 7.3). One row per shift a carer starts; ended_at is
-- set when the shift is closed. The handover collects notes by carer_id and
-- created_at within the shift, so visit_notes needs no new column.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

create table if not exists public.shifts (
  id uuid primary key default gen_random_uuid(),
  carer_id uuid references auth.users (id),
  carer_name text,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

alter table public.shifts enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'shifts'
      and policyname = 'shifts_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "shifts_authenticated_all"
      on public.shifts
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- ===== B. 020_resident_role.sql =======================================
-- 020_resident_role.sql
-- Resident app (guide chapter 10). Adds 'resident' as a valid user role and
-- links a resident's login to their residents row.
--
-- NOTE: this file is a deliberate one-off exception to "additive only".
-- user_profiles.role has a CHECK constraint limiting it to the old role
-- list; a check constraint cannot be widened in place, so it is dropped and
-- re-added with 'resident' included. No rows are changed or removed.
-- The constraint is found by its definition rather than by name, because
-- the name was auto-generated.
-- Do not edit this file after it has been run anywhere — later changes go
-- in a new numbered file.

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.user_profiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%role%'
  loop
    execute format('alter table public.user_profiles drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.user_profiles
  add constraint user_profiles_role_check
  check (role in ('superadmin', 'admin', 'staff', 'caregiver', 'family', 'resident'));

alter table public.user_profiles
  add column if not exists resident_id uuid references public.residents (id);

-- ===== B. 021_seed_resident_auth_profile.sql ==========================
-- 021_seed_resident_auth_profile.sql
-- Links a demo resident login to a profile row with role 'resident' and to
-- the first resident in the residents table.
-- Prerequisite (manual, not SQL): create the matching Supabase Auth user
-- first, in Dashboard > Authentication > Users > Add user:
--   email    resident_123@aethon.local
--   password (whatever you'll sign in with on the email/password form)
--   check "Auto Confirm User"
-- Run 020 first. Additive only. Do not edit this file after it has been run
-- anywhere — later changes go in a new numbered file.

insert into public.user_profiles (id, role, full_name, resident_id)
select
  u.id,
  'resident',
  (select first_name from public.residents order by created_at limit 1),
  (select id from public.residents order by created_at limit 1)
from auth.users u
where u.email = 'resident_123@aethon.local'
on conflict (id) do update set
  role = excluded.role,
  full_name = excluded.full_name,
  resident_id = excluded.resident_id;

-- ===== B. 022_independence_goals.sql ==================================
-- 022_independence_goals.sql
-- Independence goals (guide 10.2). The resident's own words, stored verbatim
-- as an array of { text, family_visible } objects. No status, progress or
-- achieved/failed state exists by design. family_visible defaults to false
-- in the app; family screens only ever read entries where it is true.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

alter table public.residents
  add column if not exists independence_goals jsonb not null default '[]';

-- ===== B. 023_seed_family_resident_link.sql ===========================
-- 023_seed_family_resident_link.sql
-- Links the demo family login (family_member123@aethon.local) to the same
-- resident as the demo resident login (the first row in residents), so the
-- family screen can show that resident's family-visible goals.
-- Run 020 first (adds user_profiles.resident_id). Additive only. Do not
-- edit this file after it has been run anywhere — later changes go in a
-- new numbered file.

update public.user_profiles
set resident_id = (select id from public.residents order by created_at limit 1)
where id = (select id from auth.users where email = 'family_member123@aethon.local');

-- ===== B. 024_daily_summary.sql =======================================
-- 024_daily_summary.sql
-- Resident daily summary (guide 10.3).
-- 1. medication_acks: one row per dose the resident marks taken or skipped.
--    The screen that writes them is built in 10.4; 10.3 reads them for the
--    "today" status and the consecutive-day streak. Reference only, not a
--    medication administration record.
-- 2. messages gains the columns needed to show a family message to a
--    resident and record that they saw it. The existing `content` column is
--    used as the message body, so no separate body column is added.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

create table if not exists public.medication_acks (
  id uuid primary key default gen_random_uuid(),
  medication_id uuid not null references public.medications (id) on delete cascade,
  resident_id uuid not null references public.residents (id) on delete cascade,
  status text not null check (status in ('taken', 'skipped')),
  acked_at timestamptz not null default now()
);

alter table public.medication_acks enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'medication_acks'
      and policyname = 'medication_acks_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "medication_acks_authenticated_all"
      on public.medication_acks
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

alter table public.messages
  add column if not exists resident_id uuid references public.residents (id) on delete cascade,
  add column if not exists sender_name text,
  add column if not exists sender_role text,
  add column if not exists image_url text,
  add column if not exists acknowledged_at timestamptz;

-- ===== B. 025_seed_family_message.sql =================================
-- 025_seed_family_message.sql
-- Adds one demo message from a family member to the first resident (the one
-- linked to resident_123@aethon.local), so the resident home has something
-- to acknowledge. Run 024 first. Safe to run more than once only if you
-- accept extra demo messages. Additive only. Do not edit this file after it
-- has been run anywhere — later changes go in a new numbered file.

insert into public.messages (resident_id, sender_name, sender_role, content)
select id, 'Sarah', 'family', 'Thinking of you today. Looking forward to seeing you on Sunday!'
from public.residents
order by created_at
limit 1;

-- ===== B. 026_assistance_requests.sql =================================
-- 026_assistance_requests.sql
-- Assistance requests (guide 10.5). One row per request for help made from
-- the resident home screen, naming the contact chosen for the time of day.
-- delivered records whether a notification actually reached the contact; it
-- stays false until a delivery channel exists (push tokens are out of scope
-- for now), and the resident is told so honestly.
-- Additive only. Do not edit this file after it has been run anywhere —
-- later changes go in a new numbered file.

create table if not exists public.assistance_requests (
  id uuid primary key default gen_random_uuid(),
  resident_id uuid not null references public.residents (id) on delete cascade,
  contacted_name text,
  contacted_phone text,
  escalation_level int not null default 1,
  delivered boolean not null default false,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.assistance_requests enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'assistance_requests'
      and policyname = 'assistance_requests_authenticated_all'
  ) then
    -- Dev policy: any signed-in user can read/write; anon gets nothing.
    create policy "assistance_requests_authenticated_all"
      on public.assistance_requests
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

commit;

-- ===== C. Result ============================================================
select table_schema, table_name,
       (xpath('/row/n/text()',
              query_to_xml(format('select count(*) as n from %I.%I', table_schema, table_name),
                           false, true, '')))[1]::text::int as rows
from information_schema.tables
where table_schema in ('public', 'archive_2026_09_27') and table_type = 'BASE TABLE'
order by 1, 2;
