import React, { useCallback, useRef, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, TextInput, Alert, Linking } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { useFocusEffect, useNavigation, useRoute } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RouteProp } from '@react-navigation/native';
import { supabase } from '../../lib/supabase';
import { LoadingView } from '../../components/LoadingView';
import { ErrorView } from '../../components/ErrorView';
import { EmptyView } from '../../components/EmptyView';

import type { RootStackParamList } from '../../navigation/RootNavigator';

type RecentNote = { id: string; visit_type: string | null; transcript: string | null; created_at: string };

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
}

export default function PhysicianEscalationScreen() {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const route = useRoute<RouteProp<RootStackParamList, 'PhysicianEscalation'>>();
  const { clientId, clientName, physicianEmail } = route.params;

  const [recent, setRecent] = useState<RecentNote[]>([]);
  const [carerName, setCarerName] = useState('');
  const [facilityId, setFacilityId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [reason, setReason] = useState('');
  const [reasonError, setReasonError] = useState(false);
  const [copied, setCopied] = useState(false);
  const recorded = useRef(false);

  const load = useCallback(async () => {
    setLoading(true);
    setError(false);
    try {
        const { data: userData } = await supabase.auth.getUser();
        const [notesRes, profileRes] = await Promise.all([
          supabase
            .from('visit_notes')
            .select('id, visit_type, transcript, created_at')
            .eq('resident_id', clientId)
            .order('created_at', { ascending: false })
            .limit(3),
          supabase.from('user_profiles').select('full_name, facility_id').eq('id', userData.user?.id).single(),
        ]);
        if (notesRes.error) throw notesRes.error;
        setRecent(notesRes.data ?? []);
        if (profileRes.data) {
          setCarerName(profileRes.data.full_name ?? '');
          setFacilityId(profileRes.data.facility_id ?? null);
        }
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  }, [clientId]);

  useFocusEffect(
    useCallback(() => {
      load();
    }, [load])
  );

  const subject = `Aethon: ${clientName} - physician review requested`;
  const body = [
    `Carer: ${carerName}`,
    `Date: ${new Date().toLocaleString()}`,
    `Reason: ${reason.trim()}`,
    '',
    'Recent visit notes:',
    ...recent.map(n => `${formatDate(n.created_at)} - ${n.transcript ?? ''}`),
    '',
    'Generated by Aethon, a care coordination tool. This is not a clinical alerting system.',
    'Please reply to the carer.',
  ].join('\n');

  // Either control records the escalation once: flags the most recent note
  // and adds an escalations row. "Recorded", never "sent".
  const recordEscalation = async (): Promise<boolean> => {
    if (recorded.current) return true;
    const latest = recent[0];

    if (latest) {
      const { error } = await supabase
        .from('visit_notes')
        .update({ physician_flagged: true, flag_reason: reason.trim(), physician_flagged_at: new Date().toISOString() })
        .eq('id', latest.id);
      if (error) {
        Alert.alert('Could not record escalation', error.message);
        return false;
      }
    }

    const { error } = await supabase.from('escalations').insert({
      resident_id: clientId,
      facility_id: facilityId,
      reason: reason.trim(),
      is_resolved: false,
      severity: 'physician',
      visit_note_id: latest?.id ?? null,
    });
    if (error) {
      Alert.alert('Could not record escalation', error.message);
      return false;
    }

    recorded.current = true;
    return true;
  };

  const validate = (): boolean => {
    if (!reason.trim()) {
      setReasonError(true);
      return false;
    }
    setReasonError(false);
    return true;
  };

  const finish = () => {
    navigation.navigate('ClientProfile', { clientId, clientName, escalationJustRecorded: true });
  };

  const handleOpenEmail = async () => {
    if (!validate()) return;
    if (!(await recordEscalation())) return;
    const url = `mailto:${physicianEmail ?? ''}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    try {
      await Linking.openURL(url);
    } catch {
      Alert.alert('No email app available', 'Use "Copy summary" instead and paste it wherever you need.');
    }
    finish();
  };

  const handleCopy = async () => {
    if (!validate()) return;
    if (!(await recordEscalation())) return;
    await Clipboard.setStringAsync(body);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    finish();
  };

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Feather name="arrow-left" size={22} color="#0f172a" />
        </TouchableOpacity>
      </View>

      {loading ? (
        <LoadingView message="Loading notes" />
      ) : error ? (
        <ErrorView message="Could not load recent notes" onRetry={load} />
      ) : (
        <ScrollView contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled">
          <View style={styles.headerCard}>
            <Text style={styles.headerCardTitle}>Raise with physician</Text>
            <Text style={styles.headerCardName}>{clientName}</Text>
          </View>

          <Text style={styles.label}>Recent notes</Text>
          {recent.length === 0 ? (
            <EmptyView icon="file-text" message="No notes recorded yet" />
          ) : (
            recent.map(note => (
              <View key={note.id} style={styles.noteCard}>
                <Text style={styles.noteMeta}>
                  {formatDate(note.created_at)}
                  {note.visit_type ? ` · ${note.visit_type}` : ''}
                </Text>
                <Text style={styles.noteText}>{(note.transcript ?? '').slice(0, 120)}</Text>
              </View>
            ))
          )}

          <Text style={styles.label}>Reason</Text>
          <TextInput
            style={styles.reasonInput}
            multiline
            value={reason}
            onChangeText={text => {
              setReason(text);
              if (reasonError) setReasonError(false);
            }}
            textAlignVertical="top"
          />
          {reasonError && <Text style={styles.error}>Please give a reason</Text>}

          <TouchableOpacity style={styles.primaryButton} onPress={handleOpenEmail}>
            <Feather name="mail" size={18} color="#fff" />
            <Text style={styles.primaryButtonText}>Open email</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.secondaryButton} onPress={handleCopy}>
            <Feather name="copy" size={18} color="#0f172a" />
            <Text style={styles.secondaryButtonText}>{copied ? 'Copied' : 'Copy summary'}</Text>
          </TouchableOpacity>
        </ScrollView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  header: { paddingHorizontal: 24, paddingTop: 16 },
  backButton: { minWidth: 52, minHeight: 52, alignItems: 'center', justifyContent: 'center', padding: 4, alignSelf: 'flex-start' },
  scrollContent: { padding: 20, paddingBottom: 100 },

  headerCard: { backgroundColor: '#fee2e2', borderLeftWidth: 4, borderLeftColor: '#ef4444', borderRadius: 12, padding: 18, marginBottom: 12 },
  headerCardTitle: { fontSize: 20, fontWeight: '700', color: '#ef4444' },
  headerCardName: { fontSize: 17, color: '#0f172a', marginTop: 4 },

  label: { fontSize: 17, fontWeight: '700', color: '#0f172a', marginTop: 20, marginBottom: 10 },
  none: { fontSize: 16, color: '#94a3b8', fontStyle: 'italic' },
  noteCard: { backgroundColor: '#f1f5f9', borderRadius: 10, padding: 12, marginBottom: 8 },
  noteMeta: { fontSize: 15, color: '#64748b', marginBottom: 4 },
  noteText: { fontSize: 15, color: '#0f172a', lineHeight: 21 },

  reasonInput: { height: 110, fontSize: 16, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, padding: 12, color: '#0f172a' },
  error: { fontSize: 15, color: '#ef4444', marginTop: 6 },

  primaryButton: { flexDirection: 'row', gap: 8, backgroundColor: '#3b82f6', height: 56, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 24 },
  primaryButtonText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  secondaryButton: { flexDirection: 'row', gap: 8, backgroundColor: '#f1f5f9', height: 56, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 12 },
  secondaryButtonText: { color: '#0f172a', fontSize: 17, fontWeight: '700' },
});
